-- Coin catalog seed, part 3: ancients. Re-runnable: conflicts are skipped.
-- Sets: twelve-caesars, twelve-caesars-denarii, diadochi, roman-emperors.
-- Ancient sets are one slot per ruler (year/mintmark are null, the dates are in
-- the name). The "any coin" ruler slots are shared: an Augustus in a
-- collection fills both the Twelve Caesars and the Roman Emperors sets.
-- Roman Emperors rule: anyone with coinage struck in their own name at an
-- imperial mint. Provincial-only figures (e.g. Messalina, Poppaea) are not
-- included.

insert into public.coin_types
  (slug, series, denomination, year, mintmark, variety, metal, fine_weight_oz, name)
values
  ('roman-augustus', 'Roman Imperial', null, null, null, null, null, null, 'Augustus (27 BC-AD 14)'),
  ('roman-livia', 'Roman Imperial', null, null, null, null, null, null, 'Livia (wife of Augustus)'),
  ('roman-agrippa', 'Roman Imperial', null, null, null, null, null, null, 'Agrippa (d. 12 BC)'),
  ('roman-tiberius', 'Roman Imperial', null, null, null, null, null, null, 'Tiberius (AD 14-37)'),
  ('roman-drusus', 'Roman Imperial', null, null, null, null, null, null, 'Drusus (son of Tiberius)'),
  ('roman-nero-claudius-drusus', 'Roman Imperial', null, null, null, null, null, null, 'Nero Claudius Drusus (brother of Tiberius)'),
  ('roman-antonia', 'Roman Imperial', null, null, null, null, null, null, 'Antonia (mother of Claudius)'),
  ('roman-germanicus', 'Roman Imperial', null, null, null, null, null, null, 'Germanicus (father of Caligula)'),
  ('roman-agrippina-senior', 'Roman Imperial', null, null, null, null, null, null, 'Agrippina Senior (mother of Caligula)'),
  ('roman-caligula', 'Roman Imperial', null, null, null, null, null, null, 'Caligula (37-41)'),
  ('roman-nero-and-drusus-caesars', 'Roman Imperial', null, null, null, null, null, null, 'Nero and Drusus Caesars (brothers of Caligula)'),
  ('roman-claudius', 'Roman Imperial', null, null, null, null, null, null, 'Claudius (41-54)'),
  ('roman-agrippina-junior', 'Roman Imperial', null, null, null, null, null, null, 'Agrippina Junior (wife of Claudius)'),
  ('roman-nero', 'Roman Imperial', null, null, null, null, null, null, 'Nero (54-68)'),
  ('roman-clodius-macer', 'Roman Imperial', null, null, null, null, null, null, 'Clodius Macer (usurper, 68)'),
  ('roman-galba', 'Roman Imperial', null, null, null, null, null, null, 'Galba (68-69)'),
  ('roman-otho', 'Roman Imperial', null, null, null, null, null, null, 'Otho (69)'),
  ('roman-vitellius', 'Roman Imperial', null, null, null, null, null, null, 'Vitellius (69)'),
  ('roman-vespasian', 'Roman Imperial', null, null, null, null, null, null, 'Vespasian (69-79)'),
  ('roman-domitilla', 'Roman Imperial', null, null, null, null, null, null, 'Domitilla (wife or daughter of Vespasian)'),
  ('roman-titus', 'Roman Imperial', null, null, null, null, null, null, 'Titus (79-81)'),
  ('roman-julia-titi', 'Roman Imperial', null, null, null, null, null, null, 'Julia Titi (daughter of Titus)'),
  ('roman-domitian', 'Roman Imperial', null, null, null, null, null, null, 'Domitian (81-96)'),
  ('roman-domitia', 'Roman Imperial', null, null, null, null, null, null, 'Domitia (wife of Domitian)'),
  ('roman-nerva', 'Roman Imperial', null, null, null, null, null, null, 'Nerva (96-98)'),
  ('roman-trajan', 'Roman Imperial', null, null, null, null, null, null, 'Trajan (98-117)'),
  ('roman-plotina', 'Roman Imperial', null, null, null, null, null, null, 'Plotina (wife of Trajan)'),
  ('roman-marciana', 'Roman Imperial', null, null, null, null, null, null, 'Marciana (sister of Trajan)'),
  ('roman-matidia', 'Roman Imperial', null, null, null, null, null, null, 'Matidia (niece of Trajan)'),
  ('roman-hadrian', 'Roman Imperial', null, null, null, null, null, null, 'Hadrian (117-138)'),
  ('roman-sabina', 'Roman Imperial', null, null, null, null, null, null, 'Sabina (wife of Hadrian)'),
  ('roman-aelius', 'Roman Imperial', null, null, null, null, null, null, 'Aelius (Caesar, 136-138)'),
  ('roman-antoninus-pius', 'Roman Imperial', null, null, null, null, null, null, 'Antoninus Pius (138-161)'),
  ('roman-faustina-i', 'Roman Imperial', null, null, null, null, null, null, 'Faustina I (wife of Antoninus Pius)'),
  ('roman-marcus-aurelius', 'Roman Imperial', null, null, null, null, null, null, 'Marcus Aurelius (161-180)'),
  ('roman-faustina-ii', 'Roman Imperial', null, null, null, null, null, null, 'Faustina II (wife of Marcus Aurelius)'),
  ('roman-lucius-verus', 'Roman Imperial', null, null, null, null, null, null, 'Lucius Verus (161-169)'),
  ('roman-lucilla', 'Roman Imperial', null, null, null, null, null, null, 'Lucilla (wife of Lucius Verus)'),
  ('roman-commodus', 'Roman Imperial', null, null, null, null, null, null, 'Commodus (177-192)'),
  ('roman-crispina', 'Roman Imperial', null, null, null, null, null, null, 'Crispina (wife of Commodus)'),
  ('roman-pertinax', 'Roman Imperial', null, null, null, null, null, null, 'Pertinax (193)'),
  ('roman-didius-julianus', 'Roman Imperial', null, null, null, null, null, null, 'Didius Julianus (193)'),
  ('roman-manlia-scantilla', 'Roman Imperial', null, null, null, null, null, null, 'Manlia Scantilla (wife of Didius Julianus)'),
  ('roman-didia-clara', 'Roman Imperial', null, null, null, null, null, null, 'Didia Clara (daughter of Didius Julianus)'),
  ('roman-pescennius-niger', 'Roman Imperial', null, null, null, null, null, null, 'Pescennius Niger (usurper, 193-194)'),
  ('roman-clodius-albinus', 'Roman Imperial', null, null, null, null, null, null, 'Clodius Albinus (Caesar and usurper, 193-197)'),
  ('roman-septimius-severus', 'Roman Imperial', null, null, null, null, null, null, 'Septimius Severus (193-211)'),
  ('roman-julia-domna', 'Roman Imperial', null, null, null, null, null, null, 'Julia Domna (wife of Septimius Severus)'),
  ('roman-caracalla', 'Roman Imperial', null, null, null, null, null, null, 'Caracalla (198-217)'),
  ('roman-plautilla', 'Roman Imperial', null, null, null, null, null, null, 'Plautilla (wife of Caracalla)'),
  ('roman-geta', 'Roman Imperial', null, null, null, null, null, null, 'Geta (209-211)'),
  ('roman-macrinus', 'Roman Imperial', null, null, null, null, null, null, 'Macrinus (217-218)'),
  ('roman-diadumenian', 'Roman Imperial', null, null, null, null, null, null, 'Diadumenian (218)'),
  ('roman-elagabalus', 'Roman Imperial', null, null, null, null, null, null, 'Elagabalus (218-222)'),
  ('roman-julia-paula', 'Roman Imperial', null, null, null, null, null, null, 'Julia Paula (wife of Elagabalus)'),
  ('roman-aquilia-severa', 'Roman Imperial', null, null, null, null, null, null, 'Aquilia Severa (wife of Elagabalus)'),
  ('roman-annia-faustina', 'Roman Imperial', null, null, null, null, null, null, 'Annia Faustina (wife of Elagabalus)'),
  ('roman-julia-soaemias', 'Roman Imperial', null, null, null, null, null, null, 'Julia Soaemias (mother of Elagabalus)'),
  ('roman-julia-maesa', 'Roman Imperial', null, null, null, null, null, null, 'Julia Maesa (grandmother of Elagabalus)'),
  ('roman-severus-alexander', 'Roman Imperial', null, null, null, null, null, null, 'Severus Alexander (222-235)'),
  ('roman-orbiana', 'Roman Imperial', null, null, null, null, null, null, 'Orbiana (wife of Severus Alexander)'),
  ('roman-julia-mamaea', 'Roman Imperial', null, null, null, null, null, null, 'Julia Mamaea (mother of Severus Alexander)'),
  ('roman-maximinus-i', 'Roman Imperial', null, null, null, null, null, null, 'Maximinus I (235-238)'),
  ('roman-paulina', 'Roman Imperial', null, null, null, null, null, null, 'Paulina (wife of Maximinus I)'),
  ('roman-maximus', 'Roman Imperial', null, null, null, null, null, null, 'Maximus (Caesar, 235-238)'),
  ('roman-gordian-i', 'Roman Imperial', null, null, null, null, null, null, 'Gordian I (238)'),
  ('roman-gordian-ii', 'Roman Imperial', null, null, null, null, null, null, 'Gordian II (238)'),
  ('roman-balbinus', 'Roman Imperial', null, null, null, null, null, null, 'Balbinus (238)'),
  ('roman-pupienus', 'Roman Imperial', null, null, null, null, null, null, 'Pupienus (238)'),
  ('roman-gordian-iii', 'Roman Imperial', null, null, null, null, null, null, 'Gordian III (238-244)'),
  ('roman-tranquillina', 'Roman Imperial', null, null, null, null, null, null, 'Tranquillina (wife of Gordian III)'),
  ('roman-philip-i', 'Roman Imperial', null, null, null, null, null, null, 'Philip I (244-249)'),
  ('roman-otacilia-severa', 'Roman Imperial', null, null, null, null, null, null, 'Otacilia Severa (wife of Philip I)'),
  ('roman-philip-ii', 'Roman Imperial', null, null, null, null, null, null, 'Philip II (247-249)'),
  ('roman-pacatian', 'Roman Imperial', null, null, null, null, null, null, 'Pacatian (usurper, 248)'),
  ('roman-jotapian', 'Roman Imperial', null, null, null, null, null, null, 'Jotapian (usurper, 249)'),
  ('roman-silbannacus', 'Roman Imperial', null, null, null, null, null, null, 'Silbannacus (usurper, c. 253)'),
  ('roman-trajan-decius', 'Roman Imperial', null, null, null, null, null, null, 'Trajan Decius (249-251)'),
  ('roman-herennia-etruscilla', 'Roman Imperial', null, null, null, null, null, null, 'Herennia Etruscilla (wife of Trajan Decius)'),
  ('roman-herennius-etruscus', 'Roman Imperial', null, null, null, null, null, null, 'Herennius Etruscus (251)'),
  ('roman-hostilian', 'Roman Imperial', null, null, null, null, null, null, 'Hostilian (251)'),
  ('roman-trebonianus-gallus', 'Roman Imperial', null, null, null, null, null, null, 'Trebonianus Gallus (251-253)'),
  ('roman-volusian', 'Roman Imperial', null, null, null, null, null, null, 'Volusian (251-253)'),
  ('roman-aemilian', 'Roman Imperial', null, null, null, null, null, null, 'Aemilian (253)'),
  ('roman-cornelia-supera', 'Roman Imperial', null, null, null, null, null, null, 'Cornelia Supera (wife of Aemilian)'),
  ('roman-uranius-antoninus', 'Roman Imperial', null, null, null, null, null, null, 'Uranius Antoninus (usurper, 253)'),
  ('roman-valerian-i', 'Roman Imperial', null, null, null, null, null, null, 'Valerian I (253-260)'),
  ('roman-mariniana', 'Roman Imperial', null, null, null, null, null, null, 'Mariniana (wife of Valerian I)'),
  ('roman-gallienus', 'Roman Imperial', null, null, null, null, null, null, 'Gallienus (253-268)'),
  ('roman-salonina', 'Roman Imperial', null, null, null, null, null, null, 'Salonina (wife of Gallienus)'),
  ('roman-valerian-ii', 'Roman Imperial', null, null, null, null, null, null, 'Valerian II (Caesar, 256-258)'),
  ('roman-saloninus', 'Roman Imperial', null, null, null, null, null, null, 'Saloninus (260)'),
  ('roman-macrianus', 'Roman Imperial', null, null, null, null, null, null, 'Macrianus (usurper, 260-261)'),
  ('roman-quietus', 'Roman Imperial', null, null, null, null, null, null, 'Quietus (usurper, 260-261)'),
  ('roman-regalianus', 'Roman Imperial', null, null, null, null, null, null, 'Regalianus (usurper, 260)'),
  ('roman-dryantilla', 'Roman Imperial', null, null, null, null, null, null, 'Dryantilla (wife of Regalianus)'),
  ('roman-postumus', 'Roman Imperial', null, null, null, null, null, null, 'Postumus (Gallic Empire, 260-269)'),
  ('roman-laelian', 'Roman Imperial', null, null, null, null, null, null, 'Laelian (Gallic usurper, 269)'),
  ('roman-marius', 'Roman Imperial', null, null, null, null, null, null, 'Marius (Gallic Empire, 269)'),
  ('roman-victorinus', 'Roman Imperial', null, null, null, null, null, null, 'Victorinus (Gallic Empire, 269-271)'),
  ('roman-domitianus-ii', 'Roman Imperial', null, null, null, null, null, null, 'Domitianus II (Gallic usurper, c. 271)'),
  ('roman-tetricus-i', 'Roman Imperial', null, null, null, null, null, null, 'Tetricus I (Gallic Empire, 271-274)'),
  ('roman-tetricus-ii', 'Roman Imperial', null, null, null, null, null, null, 'Tetricus II (Gallic Empire, 273-274)'),
  ('roman-claudius-ii-gothicus', 'Roman Imperial', null, null, null, null, null, null, 'Claudius II Gothicus (268-270)'),
  ('roman-quintillus', 'Roman Imperial', null, null, null, null, null, null, 'Quintillus (270)'),
  ('roman-aurelian', 'Roman Imperial', null, null, null, null, null, null, 'Aurelian (270-275)'),
  ('roman-severina', 'Roman Imperial', null, null, null, null, null, null, 'Severina (wife of Aurelian)'),
  ('roman-vabalathus', 'Roman Imperial', null, null, null, null, null, null, 'Vabalathus (Palmyra, 270-272)'),
  ('roman-zenobia', 'Roman Imperial', null, null, null, null, null, null, 'Zenobia (Palmyra, 272)'),
  ('roman-tacitus', 'Roman Imperial', null, null, null, null, null, null, 'Tacitus (275-276)'),
  ('roman-florian', 'Roman Imperial', null, null, null, null, null, null, 'Florian (276)'),
  ('roman-probus', 'Roman Imperial', null, null, null, null, null, null, 'Probus (276-282)'),
  ('roman-carus', 'Roman Imperial', null, null, null, null, null, null, 'Carus (282-283)'),
  ('roman-magnia-urbica', 'Roman Imperial', null, null, null, null, null, null, 'Magnia Urbica (wife of Carinus)'),
  ('roman-numerian', 'Roman Imperial', null, null, null, null, null, null, 'Numerian (283-284)'),
  ('roman-carinus', 'Roman Imperial', null, null, null, null, null, null, 'Carinus (283-285)'),
  ('roman-nigrinian', 'Roman Imperial', null, null, null, null, null, null, 'Nigrinian (son of Carinus)'),
  ('roman-julian-of-pannonia', 'Roman Imperial', null, null, null, null, null, null, 'Julian of Pannonia (usurper, 284-285)'),
  ('roman-diocletian', 'Roman Imperial', null, null, null, null, null, null, 'Diocletian (284-305)'),
  ('roman-maximian', 'Roman Imperial', null, null, null, null, null, null, 'Maximian (286-305, 306-308)'),
  ('roman-carausius', 'Roman Imperial', null, null, null, null, null, null, 'Carausius (Britannic usurper, 286-293)'),
  ('roman-allectus', 'Roman Imperial', null, null, null, null, null, null, 'Allectus (Britannic usurper, 293-296)'),
  ('roman-domitius-domitianus', 'Roman Imperial', null, null, null, null, null, null, 'Domitius Domitianus (usurper in Egypt, 297)'),
  ('roman-constantius-i', 'Roman Imperial', null, null, null, null, null, null, 'Constantius I (293-306)'),
  ('roman-galerius', 'Roman Imperial', null, null, null, null, null, null, 'Galerius (293-311)'),
  ('roman-galeria-valeria', 'Roman Imperial', null, null, null, null, null, null, 'Galeria Valeria (wife of Galerius)'),
  ('roman-severus-ii', 'Roman Imperial', null, null, null, null, null, null, 'Severus II (305-307)'),
  ('roman-maximinus-ii', 'Roman Imperial', null, null, null, null, null, null, 'Maximinus II (305-313)'),
  ('roman-maxentius', 'Roman Imperial', null, null, null, null, null, null, 'Maxentius (306-312)'),
  ('roman-romulus', 'Roman Imperial', null, null, null, null, null, null, 'Romulus (son of Maxentius)'),
  ('roman-domitius-alexander', 'Roman Imperial', null, null, null, null, null, null, 'Domitius Alexander (usurper in Africa, 308-310)'),
  ('roman-licinius-i', 'Roman Imperial', null, null, null, null, null, null, 'Licinius I (308-324)'),
  ('roman-licinius-ii', 'Roman Imperial', null, null, null, null, null, null, 'Licinius II (Caesar, 317-324)'),
  ('roman-valerius-valens', 'Roman Imperial', null, null, null, null, null, null, 'Valerius Valens (usurper, 316)'),
  ('roman-martinian', 'Roman Imperial', null, null, null, null, null, null, 'Martinian (usurper, 324)'),
  ('roman-constantine-i', 'Roman Imperial', null, null, null, null, null, null, 'Constantine I (306-337)'),
  ('roman-fausta', 'Roman Imperial', null, null, null, null, null, null, 'Fausta (wife of Constantine I)'),
  ('roman-helena', 'Roman Imperial', null, null, null, null, null, null, 'Helena (mother of Constantine I)'),
  ('roman-theodora', 'Roman Imperial', null, null, null, null, null, null, 'Theodora (wife of Constantius I)'),
  ('roman-crispus', 'Roman Imperial', null, null, null, null, null, null, 'Crispus (Caesar, 317-326)'),
  ('roman-delmatius', 'Roman Imperial', null, null, null, null, null, null, 'Delmatius (Caesar, 335-337)'),
  ('roman-hanniballianus', 'Roman Imperial', null, null, null, null, null, null, 'Hanniballianus (335-337)'),
  ('roman-constantine-ii', 'Roman Imperial', null, null, null, null, null, null, 'Constantine II (337-340)'),
  ('roman-constans', 'Roman Imperial', null, null, null, null, null, null, 'Constans (337-350)'),
  ('roman-constantius-ii', 'Roman Imperial', null, null, null, null, null, null, 'Constantius II (337-361)'),
  ('roman-magnentius', 'Roman Imperial', null, null, null, null, null, null, 'Magnentius (usurper, 350-353)'),
  ('roman-decentius', 'Roman Imperial', null, null, null, null, null, null, 'Decentius (Caesar of Magnentius, 350-353)'),
  ('roman-vetranio', 'Roman Imperial', null, null, null, null, null, null, 'Vetranio (usurper, 350)'),
  ('roman-nepotian', 'Roman Imperial', null, null, null, null, null, null, 'Nepotian (usurper, 350)'),
  ('roman-constantius-gallus', 'Roman Imperial', null, null, null, null, null, null, 'Constantius Gallus (Caesar, 351-354)'),
  ('roman-julian-ii', 'Roman Imperial', null, null, null, null, null, null, 'Julian II (360-363)'),
  ('roman-jovian', 'Roman Imperial', null, null, null, null, null, null, 'Jovian (363-364)'),
  ('roman-valentinian-i', 'Roman Imperial', null, null, null, null, null, null, 'Valentinian I (364-375)'),
  ('roman-valens', 'Roman Imperial', null, null, null, null, null, null, 'Valens (364-378)'),
  ('roman-procopius', 'Roman Imperial', null, null, null, null, null, null, 'Procopius (usurper, 365-366)'),
  ('roman-gratian', 'Roman Imperial', null, null, null, null, null, null, 'Gratian (367-383)'),
  ('roman-valentinian-ii', 'Roman Imperial', null, null, null, null, null, null, 'Valentinian II (375-392)'),
  ('roman-theodosius-i', 'Roman Imperial', null, null, null, null, null, null, 'Theodosius I (379-395)'),
  ('roman-aelia-flaccilla', 'Roman Imperial', null, null, null, null, null, null, 'Aelia Flaccilla (wife of Theodosius I)'),
  ('roman-magnus-maximus', 'Roman Imperial', null, null, null, null, null, null, 'Magnus Maximus (usurper, 383-388)'),
  ('roman-flavius-victor', 'Roman Imperial', null, null, null, null, null, null, 'Flavius Victor (son of Magnus Maximus)'),
  ('roman-eugenius', 'Roman Imperial', null, null, null, null, null, null, 'Eugenius (usurper, 392-394)'),
  ('roman-arcadius', 'Roman Imperial', null, null, null, null, null, null, 'Arcadius (383-408)'),
  ('roman-eudoxia', 'Roman Imperial', null, null, null, null, null, null, 'Eudoxia (wife of Arcadius)'),
  ('roman-honorius', 'Roman Imperial', null, null, null, null, null, null, 'Honorius (393-423)'),
  ('roman-constantine-iii', 'Roman Imperial', null, null, null, null, null, null, 'Constantine III (usurper, 407-411)'),
  ('roman-constans-ii', 'Roman Imperial', null, null, null, null, null, null, 'Constans II (son of Constantine III)'),
  ('roman-maximus-of-hispania', 'Roman Imperial', null, null, null, null, null, null, 'Maximus of Hispania (usurper, 409-411)'),
  ('roman-jovinus', 'Roman Imperial', null, null, null, null, null, null, 'Jovinus (usurper, 411-413)'),
  ('roman-sebastianus', 'Roman Imperial', null, null, null, null, null, null, 'Sebastianus (usurper, 412-413)'),
  ('roman-priscus-attalus', 'Roman Imperial', null, null, null, null, null, null, 'Priscus Attalus (usurper, 409-410, 414-415)'),
  ('roman-constantius-iii', 'Roman Imperial', null, null, null, null, null, null, 'Constantius III (421)'),
  ('roman-galla-placidia', 'Roman Imperial', null, null, null, null, null, null, 'Galla Placidia (mother of Valentinian III)'),
  ('roman-johannes', 'Roman Imperial', null, null, null, null, null, null, 'Johannes (usurper, 423-425)'),
  ('roman-theodosius-ii', 'Roman Imperial', null, null, null, null, null, null, 'Theodosius II (402-450)'),
  ('roman-aelia-eudocia', 'Roman Imperial', null, null, null, null, null, null, 'Aelia Eudocia (wife of Theodosius II)'),
  ('roman-aelia-pulcheria', 'Roman Imperial', null, null, null, null, null, null, 'Aelia Pulcheria (sister of Theodosius II)'),
  ('roman-valentinian-iii', 'Roman Imperial', null, null, null, null, null, null, 'Valentinian III (425-455)'),
  ('roman-licinia-eudoxia', 'Roman Imperial', null, null, null, null, null, null, 'Licinia Eudoxia (wife of Valentinian III)'),
  ('roman-honoria', 'Roman Imperial', null, null, null, null, null, null, 'Honoria (sister of Valentinian III)'),
  ('roman-marcian', 'Roman Imperial', null, null, null, null, null, null, 'Marcian (450-457)'),
  ('roman-petronius-maximus', 'Roman Imperial', null, null, null, null, null, null, 'Petronius Maximus (455)'),
  ('roman-avitus', 'Roman Imperial', null, null, null, null, null, null, 'Avitus (455-456)'),
  ('roman-leo-i', 'Roman Imperial', null, null, null, null, null, null, 'Leo I (457-474)'),
  ('roman-verina', 'Roman Imperial', null, null, null, null, null, null, 'Verina (wife of Leo I)'),
  ('roman-majorian', 'Roman Imperial', null, null, null, null, null, null, 'Majorian (457-461)'),
  ('roman-libius-severus', 'Roman Imperial', null, null, null, null, null, null, 'Libius Severus (461-465)'),
  ('roman-anthemius', 'Roman Imperial', null, null, null, null, null, null, 'Anthemius (467-472)'),
  ('roman-euphemia', 'Roman Imperial', null, null, null, null, null, null, 'Euphemia (wife of Anthemius)'),
  ('roman-olybrius', 'Roman Imperial', null, null, null, null, null, null, 'Olybrius (472)'),
  ('roman-glycerius', 'Roman Imperial', null, null, null, null, null, null, 'Glycerius (473-474)'),
  ('roman-julius-nepos', 'Roman Imperial', null, null, null, null, null, null, 'Julius Nepos (474-475)'),
  ('roman-leo-ii', 'Roman Imperial', null, null, null, null, null, null, 'Leo II (474)'),
  ('roman-zeno', 'Roman Imperial', null, null, null, null, null, null, 'Zeno (474-491)'),
  ('roman-basiliscus', 'Roman Imperial', null, null, null, null, null, null, 'Basiliscus (475-476)'),
  ('roman-zenonis', 'Roman Imperial', null, null, null, null, null, null, 'Zenonis (wife of Basiliscus)'),
  ('roman-romulus-augustulus', 'Roman Imperial', null, null, null, null, null, null, 'Romulus Augustulus (475-476)'),
  ('roman-julius-caesar', 'Roman Imperatorial', null, null, null, null, null, null, 'Julius Caesar (d. 44 BC)'),
  ('roman-denarius-julius-caesar', 'Roman Imperatorial', 'Denarius', null, null, null, 'silver', null, 'Julius Caesar Denarius'),
  ('roman-denarius-augustus', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Augustus Denarius'),
  ('roman-denarius-tiberius', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Tiberius Denarius'),
  ('roman-denarius-caligula', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Caligula Denarius'),
  ('roman-denarius-claudius', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Claudius Denarius'),
  ('roman-denarius-nero', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Nero Denarius'),
  ('roman-denarius-galba', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Galba Denarius'),
  ('roman-denarius-otho', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Otho Denarius'),
  ('roman-denarius-vitellius', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Vitellius Denarius'),
  ('roman-denarius-vespasian', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Vespasian Denarius'),
  ('roman-denarius-titus', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Titus Denarius'),
  ('roman-denarius-domitian', 'Roman Imperial', 'Denarius', null, null, null, 'silver', null, 'Domitian Denarius'),
  ('diadochi-philip-iii-arrhidaeus', 'Diadochi', null, null, null, null, null, null, 'Philip III Arrhidaeus (323-317 BC)'),
  ('diadochi-alexander-iv', 'Diadochi', null, null, null, null, null, null, 'Alexander IV (323-310 BC)'),
  ('diadochi-antigonus-i-monophthalmus', 'Diadochi', null, null, null, null, null, null, 'Antigonus I Monophthalmus (306-301 BC)'),
  ('diadochi-ptolemy-i-soter', 'Diadochi', null, null, null, null, null, null, 'Ptolemy I Soter (305-282 BC)'),
  ('diadochi-seleucus-i-nicator', 'Diadochi', null, null, null, null, null, null, 'Seleucus I Nicator (305-281 BC)'),
  ('diadochi-cassander', 'Diadochi', null, null, null, null, null, null, 'Cassander (305-297 BC)'),
  ('diadochi-lysimachus', 'Diadochi', null, null, null, null, null, null, 'Lysimachus (305-281 BC)'),
  ('diadochi-demetrius-i-poliorcetes', 'Diadochi', null, null, null, null, null, null, 'Demetrius I Poliorcetes (294-288 BC)')
on conflict (slug) do nothing;

insert into public.sets (slug, name, series, description)
values
  ('twelve-caesars', 'Twelve Caesars', 'Roman Imperial', 'Suetonius'' Twelve Caesars, Julius Caesar to Domitian - one coin of each ruler, any denomination or metal.'),
  ('twelve-caesars-denarii', 'Twelve Caesars in Silver', 'Roman Imperial', 'Suetonius'' Twelve Caesars, Julius Caesar to Domitian - one silver denarius of each.'),
  ('diadochi', 'The Diadochi', 'Diadochi', 'Alexander the Great''s heirs and successors: Philip III, Alexander IV and the six generals who carved up his empire - one coin of each, any denomination.'),
  ('roman-emperors', 'Roman Emperors', 'Roman Imperial', 'Every emperor, empress, Caesar and usurper with coinage in their own name, Augustus to Romulus Augustulus (476) - 197 rulers, one coin of each, any denomination.')
on conflict (slug) do nothing;

insert into public.set_members (set_id, coin_type_id, sort_order)
select s.id, ct.id, m.ord
from public.sets s
join (values
    ('roman-julius-caesar', 1),
    ('roman-augustus', 2),
    ('roman-tiberius', 3),
    ('roman-caligula', 4),
    ('roman-claudius', 5),
    ('roman-nero', 6),
    ('roman-galba', 7),
    ('roman-otho', 8),
    ('roman-vitellius', 9),
    ('roman-vespasian', 10),
    ('roman-titus', 11),
    ('roman-domitian', 12)
  ) as m(slug, ord) on true
join public.coin_types ct on ct.slug = m.slug
where s.slug = 'twelve-caesars'
on conflict (set_id, coin_type_id) do nothing;

insert into public.set_members (set_id, coin_type_id, sort_order)
select s.id, ct.id, m.ord
from public.sets s
join (values
    ('roman-denarius-julius-caesar', 1),
    ('roman-denarius-augustus', 2),
    ('roman-denarius-tiberius', 3),
    ('roman-denarius-caligula', 4),
    ('roman-denarius-claudius', 5),
    ('roman-denarius-nero', 6),
    ('roman-denarius-galba', 7),
    ('roman-denarius-otho', 8),
    ('roman-denarius-vitellius', 9),
    ('roman-denarius-vespasian', 10),
    ('roman-denarius-titus', 11),
    ('roman-denarius-domitian', 12)
  ) as m(slug, ord) on true
join public.coin_types ct on ct.slug = m.slug
where s.slug = 'twelve-caesars-denarii'
on conflict (set_id, coin_type_id) do nothing;

insert into public.set_members (set_id, coin_type_id, sort_order)
select s.id, ct.id, m.ord
from public.sets s
join (values
    ('diadochi-philip-iii-arrhidaeus', 1),
    ('diadochi-alexander-iv', 2),
    ('diadochi-antigonus-i-monophthalmus', 3),
    ('diadochi-ptolemy-i-soter', 4),
    ('diadochi-seleucus-i-nicator', 5),
    ('diadochi-cassander', 6),
    ('diadochi-lysimachus', 7),
    ('diadochi-demetrius-i-poliorcetes', 8)
  ) as m(slug, ord) on true
join public.coin_types ct on ct.slug = m.slug
where s.slug = 'diadochi'
on conflict (set_id, coin_type_id) do nothing;

insert into public.set_members (set_id, coin_type_id, sort_order)
select s.id, ct.id, m.ord
from public.sets s
join (values
    ('roman-augustus', 1),
    ('roman-livia', 2),
    ('roman-agrippa', 3),
    ('roman-tiberius', 4),
    ('roman-drusus', 5),
    ('roman-nero-claudius-drusus', 6),
    ('roman-antonia', 7),
    ('roman-germanicus', 8),
    ('roman-agrippina-senior', 9),
    ('roman-caligula', 10),
    ('roman-nero-and-drusus-caesars', 11),
    ('roman-claudius', 12),
    ('roman-agrippina-junior', 13),
    ('roman-nero', 14),
    ('roman-clodius-macer', 15),
    ('roman-galba', 16),
    ('roman-otho', 17),
    ('roman-vitellius', 18),
    ('roman-vespasian', 19),
    ('roman-domitilla', 20),
    ('roman-titus', 21),
    ('roman-julia-titi', 22),
    ('roman-domitian', 23),
    ('roman-domitia', 24),
    ('roman-nerva', 25),
    ('roman-trajan', 26),
    ('roman-plotina', 27),
    ('roman-marciana', 28),
    ('roman-matidia', 29),
    ('roman-hadrian', 30),
    ('roman-sabina', 31),
    ('roman-aelius', 32),
    ('roman-antoninus-pius', 33),
    ('roman-faustina-i', 34),
    ('roman-marcus-aurelius', 35),
    ('roman-faustina-ii', 36),
    ('roman-lucius-verus', 37),
    ('roman-lucilla', 38),
    ('roman-commodus', 39),
    ('roman-crispina', 40),
    ('roman-pertinax', 41),
    ('roman-didius-julianus', 42),
    ('roman-manlia-scantilla', 43),
    ('roman-didia-clara', 44),
    ('roman-pescennius-niger', 45),
    ('roman-clodius-albinus', 46),
    ('roman-septimius-severus', 47),
    ('roman-julia-domna', 48),
    ('roman-caracalla', 49),
    ('roman-plautilla', 50),
    ('roman-geta', 51),
    ('roman-macrinus', 52),
    ('roman-diadumenian', 53),
    ('roman-elagabalus', 54),
    ('roman-julia-paula', 55),
    ('roman-aquilia-severa', 56),
    ('roman-annia-faustina', 57),
    ('roman-julia-soaemias', 58),
    ('roman-julia-maesa', 59),
    ('roman-severus-alexander', 60),
    ('roman-orbiana', 61),
    ('roman-julia-mamaea', 62),
    ('roman-maximinus-i', 63),
    ('roman-paulina', 64),
    ('roman-maximus', 65),
    ('roman-gordian-i', 66),
    ('roman-gordian-ii', 67),
    ('roman-balbinus', 68),
    ('roman-pupienus', 69),
    ('roman-gordian-iii', 70),
    ('roman-tranquillina', 71),
    ('roman-philip-i', 72),
    ('roman-otacilia-severa', 73),
    ('roman-philip-ii', 74),
    ('roman-pacatian', 75),
    ('roman-jotapian', 76),
    ('roman-silbannacus', 77),
    ('roman-trajan-decius', 78),
    ('roman-herennia-etruscilla', 79),
    ('roman-herennius-etruscus', 80),
    ('roman-hostilian', 81),
    ('roman-trebonianus-gallus', 82),
    ('roman-volusian', 83),
    ('roman-aemilian', 84),
    ('roman-cornelia-supera', 85),
    ('roman-uranius-antoninus', 86),
    ('roman-valerian-i', 87),
    ('roman-mariniana', 88),
    ('roman-gallienus', 89),
    ('roman-salonina', 90),
    ('roman-valerian-ii', 91),
    ('roman-saloninus', 92),
    ('roman-macrianus', 93),
    ('roman-quietus', 94),
    ('roman-regalianus', 95),
    ('roman-dryantilla', 96),
    ('roman-postumus', 97),
    ('roman-laelian', 98),
    ('roman-marius', 99),
    ('roman-victorinus', 100),
    ('roman-domitianus-ii', 101),
    ('roman-tetricus-i', 102),
    ('roman-tetricus-ii', 103),
    ('roman-claudius-ii-gothicus', 104),
    ('roman-quintillus', 105),
    ('roman-aurelian', 106),
    ('roman-severina', 107),
    ('roman-vabalathus', 108),
    ('roman-zenobia', 109),
    ('roman-tacitus', 110),
    ('roman-florian', 111),
    ('roman-probus', 112),
    ('roman-carus', 113),
    ('roman-magnia-urbica', 114),
    ('roman-numerian', 115),
    ('roman-carinus', 116),
    ('roman-nigrinian', 117),
    ('roman-julian-of-pannonia', 118),
    ('roman-diocletian', 119),
    ('roman-maximian', 120),
    ('roman-carausius', 121),
    ('roman-allectus', 122),
    ('roman-domitius-domitianus', 123),
    ('roman-constantius-i', 124),
    ('roman-galerius', 125),
    ('roman-galeria-valeria', 126),
    ('roman-severus-ii', 127),
    ('roman-maximinus-ii', 128),
    ('roman-maxentius', 129),
    ('roman-romulus', 130),
    ('roman-domitius-alexander', 131),
    ('roman-licinius-i', 132),
    ('roman-licinius-ii', 133),
    ('roman-valerius-valens', 134),
    ('roman-martinian', 135),
    ('roman-constantine-i', 136),
    ('roman-fausta', 137),
    ('roman-helena', 138),
    ('roman-theodora', 139),
    ('roman-crispus', 140),
    ('roman-delmatius', 141),
    ('roman-hanniballianus', 142),
    ('roman-constantine-ii', 143),
    ('roman-constans', 144),
    ('roman-constantius-ii', 145),
    ('roman-magnentius', 146),
    ('roman-decentius', 147),
    ('roman-vetranio', 148),
    ('roman-nepotian', 149),
    ('roman-constantius-gallus', 150),
    ('roman-julian-ii', 151),
    ('roman-jovian', 152),
    ('roman-valentinian-i', 153),
    ('roman-valens', 154),
    ('roman-procopius', 155),
    ('roman-gratian', 156),
    ('roman-valentinian-ii', 157),
    ('roman-theodosius-i', 158),
    ('roman-aelia-flaccilla', 159),
    ('roman-magnus-maximus', 160),
    ('roman-flavius-victor', 161),
    ('roman-eugenius', 162),
    ('roman-arcadius', 163),
    ('roman-eudoxia', 164),
    ('roman-honorius', 165),
    ('roman-constantine-iii', 166),
    ('roman-constans-ii', 167),
    ('roman-maximus-of-hispania', 168),
    ('roman-jovinus', 169),
    ('roman-sebastianus', 170),
    ('roman-priscus-attalus', 171),
    ('roman-constantius-iii', 172),
    ('roman-galla-placidia', 173),
    ('roman-johannes', 174),
    ('roman-theodosius-ii', 175),
    ('roman-aelia-eudocia', 176),
    ('roman-aelia-pulcheria', 177),
    ('roman-valentinian-iii', 178),
    ('roman-licinia-eudoxia', 179),
    ('roman-honoria', 180),
    ('roman-marcian', 181),
    ('roman-petronius-maximus', 182),
    ('roman-avitus', 183),
    ('roman-leo-i', 184),
    ('roman-verina', 185),
    ('roman-majorian', 186),
    ('roman-libius-severus', 187),
    ('roman-anthemius', 188),
    ('roman-euphemia', 189),
    ('roman-olybrius', 190),
    ('roman-glycerius', 191),
    ('roman-julius-nepos', 192),
    ('roman-leo-ii', 193),
    ('roman-zeno', 194),
    ('roman-basiliscus', 195),
    ('roman-zenonis', 196),
    ('roman-romulus-augustulus', 197)
  ) as m(slug, ord) on true
join public.coin_types ct on ct.slug = m.slug
where s.slug = 'roman-emperors'
on conflict (set_id, coin_type_id) do nothing;
